- name: initialize the cluster
  command: kubeadm init --pod-network-cidr=10.244.0.0/16
  args:
    creates: /home/kube/cluster_initialized.log
  register: kubeadm_init_raw

- name: save kubeadm init output to a file
  copy:
    content: "stdout:\n{{ kubeadm_init_raw.stdout }}\n\nstderr:\n{{ kubeadm_init_raw.stderr }}"
    dest: /home/kube/cluster_initialized.log
  when: kubeadm_init_raw.changed

- name: create .kube directory
  file:
    path: /home/kube/.kube
    state: directory
    mode: 0755
    owner: kube
    group: kube

- name: copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/kube/.kube/config
    remote_src: true
    owner: kube
    group: kube

- name: install weave cni
  become: true
  become_user: kube
  shell: |
    kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml

- name: remove control plane taints
  become: true
  become_user: kube
  shell: |  # attempt to delete the taint, then exit successfully if the only error is that the taint doesn't exist
    status=$(kubectl taint nodes --all node-role.kubernetes.io/control-plane- \
    2>&1 >/dev/null) || [ "$status" = "error: taint \"node-role.kubernetes.io/control-plane\" not found" ]
