- name: initialize the cluster
  command: kubeadm init --pod-network-cidr=10.244.0.0/16
  args:
    creates: /home/kube/cluster_initialized.log
  register: kubeadm_init_raw

- name: save kubeadm init output to a file
  copy:
    content: "stdout:\n{{ kubeadm_init_raw.stdout }}\n\nstderr:\n{{ kubeadm_init_raw.stderr }}"
    dest: /home/kube/cluster_initialized.log
  when: kubeadm_init_raw.changed

- name: create .kube directory
  file:
    path: /home/kube/.kube
    state: directory
    mode: 0755
    owner: kube
    group: kube

- name: copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/kube/.kube/config
    remote_src: true
    owner: kube
    group: kube

- name: install calico network
  become: true
  become_user: kube
  shell: |  # using `create` is recommended by tigera if `apply` times out
    kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.0/manifests/tigera-operator.yaml
    kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.0/manifests/custom-resources.yaml

- name: validate calico install
  become: true
  become_user: kube
  shell: "[ $(kubectl get pods -n tigera-operator | wc -l) = '0' ] && false"

- name: remove control plane taints # TODO check if taint exists first
  become: true
  become_user: kube
  shell: kubectl taint nodes --all node-role.kubernetes.io/control-plane-
